
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.rapidservice.rapidservicequote;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-11-11T20:32:13.900-05:00
 * Generated source version: 2.7.6
 * 
 */

@javax.jws.WebService(
                      serviceName = "RapidService",
                      portName = "RapidService",
                      targetNamespace = "http://www.rapidservice.com/rapidserviceQuote/",
                      wsdlLocation = "http://localhost:8081/rapidservice/services/rapidserviceQuoteSOAP2?wsdl",
                      endpointInterface = "com.rapidservice.rapidservicequote.RapidService")
                      
public class RapidServiceImpl implements RapidService {

    private static final Logger LOG = Logger.getLogger(RapidServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.rapidservice.rapidservicequote.RapidService#processQuote(com.rapidservice.rapidservicequote.ProcessQuoteElement  parameters )*
     */
    public com.rapidservice.rapidservicequote.ProcessQuoteResponseElement processQuote(ProcessQuoteElement parameters) { 
        LOG.info("Executing operation processQuote");
        System.out.println(parameters);
        try {
            com.rapidservice.rapidservicequote.ProcessQuoteResponseElement _return = new com.rapidservice.rapidservicequote.ProcessQuoteResponseElement();
            com.rapidservice.rapidservicequote.Quote _returnResult = new com.rapidservice.rapidservicequote.Quote();
            _returnResult.setSupplierPrice("120000");
            _return.setResult(_returnResult);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.rapidservice.rapidservicequote.RapidService#orderQuoute(com.rapidservice.rapidservicequote.OrderQuouteElement  parameters )*
     */
    public com.rapidservice.rapidservicequote.OrderQuouteResponseElement orderQuoute(OrderQuouteElement parameters) { 
        LOG.info("Executing operation orderQuoute");
        System.out.println(parameters);
        try {
            com.rapidservice.rapidservicequote.OrderQuouteResponseElement _return = new com.rapidservice.rapidservicequote.OrderQuouteResponseElement();
            _return.setResult(true);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
