package com.rapidservice.rapidservicequote;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-11-11T20:32:13.988-05:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://www.rapidservice.com/rapidserviceQuote/", name = "RapidService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface RapidService {

    @WebResult(name = "processQuoteResponseElement", targetNamespace = "http://www.rapidservice.com/rapidserviceQuote/", partName = "parameters")
    @WebMethod(action = "http://www.rapidservice.com/rapidserviceQuote/rapidserviceQuoteService")
    public ProcessQuoteResponseElement processQuote(
        @WebParam(partName = "parameters", name = "processQuoteElement", targetNamespace = "http://www.rapidservice.com/rapidserviceQuote/")
        ProcessQuoteElement parameters
    );

    @WebResult(name = "orderQuouteResponseElement", targetNamespace = "http://www.rapidservice.com/rapidserviceQuote/", partName = "parameters")
    @WebMethod(action = "http://www.rapidservice.com/rapidserviceQuote/rapidserviceQuoteService")
    public OrderQuouteResponseElement orderQuoute(
        @WebParam(partName = "parameters", name = "orderQuouteElement", targetNamespace = "http://www.rapidservice.com/rapidserviceQuote/")
        OrderQuouteElement parameters
    );
}
