package com.sony.sonyquote;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-11-11T12:23:28.378-05:00
 * Generated source version: 2.7.6
 * 
 */
@WebServiceClient(name = "sonyQuote", 
                  wsdlLocation = "http://localhost:8081/sony/services/sonyQuoteSOAP?wsdl",
                  targetNamespace = "http://www.sony.com/sonyQuote/") 
public class SonyQuote extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.sony.com/sonyQuote/", "sonyQuote");
    public final static QName SonyQuoteSOAP2 = new QName("http://www.sony.com/sonyQuote/", "sonyQuoteSOAP2");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8081/sony/services/sonyQuoteSOAP?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SonyQuote.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8081/sony/services/sonyQuoteSOAP?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SonyQuote(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SonyQuote(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SonyQuote() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns SonyQuoteService
     */
    @WebEndpoint(name = "sonyQuoteSOAP2")
    public SonyQuoteService getSonyQuoteSOAP2() {
        return super.getPort(SonyQuoteSOAP2, SonyQuoteService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SonyQuoteService
     */
    @WebEndpoint(name = "sonyQuoteSOAP2")
    public SonyQuoteService getSonyQuoteSOAP2(WebServiceFeature... features) {
        return super.getPort(SonyQuoteSOAP2, SonyQuoteService.class, features);
    }

}
