package com.mycompany.sp.definitions;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-11-10T01:47:01.915-05:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://mycompany.com/sp/definitions", name = "CustomerBinding")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CustomerBinding {

    @WebResult(name = "GetCustomerResponse", targetNamespace = "http://mycompany.com/sp/definitions", partName = "GetCustomerRes")
    @WebMethod(operationName = "GetCustomer", action = "http://mycompany.com/GetCustomer")
    public GetCustomerResponse getCustomer(
        @WebParam(partName = "GetCustomerReq", name = "GetCustomerRequest", targetNamespace = "http://mycompany.com/sp/definitions")
        GetCustomerRequest getCustomerReq
    );

    @WebResult(name = "RegisterCustomerResponse", targetNamespace = "http://mycompany.com/sp/definitions", partName = "RegisterCustomerRes")
    @WebMethod(operationName = "RegisterCustomer", action = "http://mycompany.com/RegisterCustomer")
    public RegisterCustomerResponse registerCustomer(
        @WebParam(partName = "RegisterCustomerReq", name = "RegisterCustomerRequest", targetNamespace = "http://mycompany.com/sp/definitions")
        RegisterCustomerRequest registerCustomerReq
    );
}
