package com.sony.sonyquote;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-11-11T12:23:28.369-05:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://www.sony.com/sonyQuote/", name = "SonyQuoteService")
@XmlSeeAlso({com.oracle.xmlns.sonyquoteservice.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SonyQuoteService {

    @WebResult(name = "SonyQuoteServiceProcessResponse", targetNamespace = "http://xmlns.oracle.com/SonyQuoteService", partName = "payload")
    @WebMethod(action = "http://www.sony.com/sonyQuote/SonyQuoteService")
    public com.oracle.xmlns.sonyquoteservice.SonyQuoteServiceProcessResponse initiate(
        @WebParam(partName = "payload", name = "SonyQuoteServiceProcessRequest", targetNamespace = "http://xmlns.oracle.com/SonyQuoteService")
        com.oracle.xmlns.sonyquoteservice.SonyQuoteServiceProcessRequest payload
    );
}
