
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.sony.sony;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-11-11T12:33:33.495-05:00
 * Generated source version: 2.7.6
 * 
 */

@javax.jws.WebService(
                      serviceName = "sony",
                      portName = "sonySOAP",
                      targetNamespace = "http://www.sony.com/sony/",
                      wsdlLocation = "http://localhost:8081/sony/services/sonySOAP?wsdl",
                      endpointInterface = "com.sony.sony.SonyOrderService")
                      
public class SonyOrderServiceImpl implements SonyOrderService {

    private static final Logger LOG = Logger.getLogger(SonyOrderServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.sony.sony.SonyOrderService#orderQuoute(com.sony.sony.OrderQuouteElement  parameters )*
     */
    public com.sony.sony.OrderQuouteResponseElement orderQuoute(OrderQuouteElement parameters) { 
        LOG.info("Executing operation orderQuoute");
        System.out.println(parameters);
        try {
            com.sony.sony.OrderQuouteResponseElement _return = new com.sony.sony.OrderQuouteResponseElement();
            _return.setResult(true);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
