
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.mycompany.sp.definitions;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-11-03T18:41:30.790-05:00
 * Generated source version: 2.7.6
 * 
 */

@javax.jws.WebService(
                      serviceName = "Order",
                      portName = "orderServicePort",
                      targetNamespace = "http://mycompany.com/sp/definitions",
                      wsdlLocation = "http://localhost:8081/orders/services/orderServicePort?wsdl",
                      endpointInterface = "com.mycompany.sp.definitions.OrderBinding")
                      
public class OrderBindingImpl implements OrderBinding {

    private static final Logger LOG = Logger.getLogger(OrderBindingImpl.class.getName());

    /* (non-Javadoc)
     * @see com.mycompany.sp.definitions.OrderBinding#getOrder(com.mycompany.sp.definitions.GetOrderRequest  getOrderRq )*
     */
    public com.mycompany.sp.definitions.GetOrderResponse getOrder(GetOrderRequest getOrderRq) { 
        LOG.info("Executing operation getOrder");
        System.out.println(getOrderRq);
        try {
            com.mycompany.sp.definitions.GetOrderResponse _return = new com.mycompany.sp.definitions.GetOrderResponse();
            com.mycompany.sp.definitions.GetOrderRs _returnGetOrderRs = new com.mycompany.sp.definitions.GetOrderRs();
            java.util.List<com.mycompany.sp.definitions.OrderType> _returnGetOrderRsOrders = new java.util.ArrayList<com.mycompany.sp.definitions.OrderType>();
            com.mycompany.sp.definitions.OrderType _returnGetOrderRsOrdersVal1 = new com.mycompany.sp.definitions.OrderType();
            _returnGetOrderRsOrdersVal1.setCustId("CustId-233773891");
            _returnGetOrderRsOrdersVal1.setOrdId("OrdId-876936767");
            _returnGetOrderRsOrdersVal1.setOrderDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-11-03T18:41:30.830-05:00"));
            _returnGetOrderRsOrdersVal1.setPrice(Integer.valueOf(603753518));
            _returnGetOrderRsOrdersVal1.setStatus("Status-1859409795");
            _returnGetOrderRsOrdersVal1.setComments("Comments-726380469");
            _returnGetOrderRsOrders.add(_returnGetOrderRsOrdersVal1);
            _returnGetOrderRs.getOrders().addAll(_returnGetOrderRsOrders);
            _return.setGetOrderRs(_returnGetOrderRs);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.mycompany.sp.definitions.OrderBinding#createOrder(com.mycompany.sp.definitions.CreateOrderRequest  createOrderRq )*
     */
    public com.mycompany.sp.definitions.CreateOrderResponse createOrder(CreateOrderRequest createOrderRq) { 
        LOG.info("Executing operation createOrder");
        System.out.println(createOrderRq);
        try {
            com.mycompany.sp.definitions.CreateOrderResponse _return = new com.mycompany.sp.definitions.CreateOrderResponse();
            com.mycompany.sp.definitions.CreateOrderRs _returnCreateOrderRs = new com.mycompany.sp.definitions.CreateOrderRs();
            _returnCreateOrderRs.setAck(-3681450807525728576l);
            _return.setCreateOrderRs(_returnCreateOrderRs);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
